version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - web-angular
    tty: true

networks:
  web-angular:
    driver: bridge
